server:
  port: 8081

spring:
  application:
    name: sample-spring-webflux

  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  threads:
    virtual:
      enabled: true

logging:
  level:
    root: INFO
    com.otel.sample: DEBUG
